Leticia/intro screen to figma
ucfcs/Fall2022-Group20 pull request #156
Opened 2023-02-23 22:17 UTC by leticiavrbarbosa

Could not find a mini game screen in the app, not sure if we have this. The backgrounds are working and have been tested.

2023-02-24 05:44 UTC, RuthShryock requested changes
UI looks good, branch is not updated to main and is breaking due to some conflicts.

2023-02-24 05:46 UTC, RuthShryock commented
Also our mini game is the quiz, sorry for the confusion; so you covered everything for this ticket.

2023-03-01 18:50 UTC, RuthShryock approved these changes

2023-03-01 18:59 UTC, mackorooji8 approved these changes
Looks good 👍

2023-03-01 19:00 UTC, merged